# Ativar atualização automática
auto-update: true

# Limite de carregadores de chunk que cada jogador pode colocar
# Defina como 0 para não ter limite
max-chunk-loaders: 8

# Complexidade de rede GPS necessária para cada carregador de chunk
gps-complexity-per-loader: 7500

# Ativar os blocos fantasmas
ghost-blocks: true

# Ativar os monstros do FoxyMachines
# Ao desativar, a receita de alguns itens muda e outros itens são removidos
custom-mobs: true

# Quantidade máxima de blocos que a varinha de preenchimento pode preencher de uma vez
max-fill-wand-blocks: 4096

## Detalhes da lista branca e da lista negra da varinha de preenchimento
# As listas contêm materiais (Material) ou tags (Tag)
# Você pode encontrar todos os materiais (Material) dos itens aqui:
#   - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# E as tags (Tag) vanilla ou tags do Slimefun (SlimefunTag) aqui:
#   - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Tag.html
#   - https://slimefun.github.io/javadocs/Slimefun4/docs/io/github/thebusybiscuit/slimefun4/utils/tags/SlimefunTag.html
# Se o nome do material coincidir com o nome de uma tag, apenas o material é considerado
#
# A varinha de preenchimento sempre permitirá qualquer material da lista branca (prioridade máxima)
# Quando o material não estiver na lista branca, as seguintes condições são verificadas:
# - O material é um bloco
# - O material bloqueia totalmente a luz
# - O material não está na lista negra
# Quando todas essas condições forem atendidas, o uso do material é permitido

# Lista branca da varinha de preenchimento
fill-wand-white-list:
  - LEAVES
  - GLASS_BLOCKS

# Lista negra da varinha de preenchimento
fill-wand-black-list:
  - BARRIER
  - SPAWNER
  - COMMAND_BLOCKS
  - STRUCTURE_BLOCK
  - JIGSAW

# Quantidade de blocos que a varinha de esponja pode remover de uma vez
max-sponge-wand-blocks: 16384

# Criaturas usadas nas missões, escolhidas aleatoriamente desta lista
# Deve ser um EntityType válido
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
quest-mobs:
  - BAT
  - BEE
  - BLAZE
  - CAT
  - CHICKEN
  - CAVE_SPIDER
  - COD
  - COW
  - CREEPER
  - DOLPHIN
  - DONKEY
  - DROWNED
  - ENDERMAN
  - GHAST
  - GUARDIAN
  - HOGLIN
  - HUSK
  - HORSE
  - IRON_GOLEM
  - LLAMA
  - MAGMA_CUBE
  - MUSHROOM_COW
  - OCELOT
  - PANDA
  - PARROT
  - PHANTOM
  - PIG
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - POLAR_BEAR
  - PUFFERFISH
  - RABBIT
  - SALMON
  - SHEEP
  - SILVERFISH
  - SKELETON
  - SLIME
  - SNOWMAN
  - SPIDER
  - SQUID
  - STRAY
  - STRIDER
  - TURTLE
  - TROPICAL_FISH
  - WITCH
  - WITHER_SKELETON
  - WOLF
  - ZOGLIN
  - ZOMBIE
  - ZOMBIFIED_PIGLIN
  - FOX

# Lista negra da Runa Inquebrável
# Você pode impedir que a Runa Inquebrável funcione em itens específicos de outros addons
unbreakable-rune-blacklist:
  InfinityExpansion:
    - BASIC_STRAINER
    - ADVANCED_STRAINER
    - REINFORCED_STRAINER
